CREATE TABLE order_statuses (
    order_id BIGSERIAL REFERENCES orders (id) ON DELETE CASCADE NOT NULL,
    status_id BIGSERIAL REFERENCES order_status (id) ON DELETE CASCADE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);