CREATE TABLE order_product (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGSERIAL REFERENCES orders (id) ON DELETE CASCADE NOT NULL,
    product_id BIGSERIAL REFERENCES product (id) ON DELETE CASCADE NOT NULL,
    unit_price DOUBLE PRECISION DEFAULT 0 NOT NULL,
    product_count BIGINT DEFAULT 0 NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);