CREATE TABLE city (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    state_id BIGSERIAL REFERENCES states (id) ON DELETE CASCADE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);