CREATE TABLE states (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    country_id BIGSERIAL REFERENCES country (id) ON DELETE CASCADE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);