CREATE TABLE payment (
    id BIGSERIAL PRIMARY KEY,
    holder_name TEXT NOT NULL,
    card_number TEXT NOT NULL,
    expiration TEXT UNIQUE NOT NULL,
    cvv TEXT NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);